config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  get 'about', to: 'users#about'
  get 'before_use', to: 'users#before_use'
  get 'terms_of_use', to: 'users#terms_of_use'
  get 'privacy_policy', to: 'users#privacy_policy'
  post 'set_agree_cookie', to: 'users#set_agreement'
  resources :users, only: %i[index create] do
    resource :easy_medical_checkups, only: %i[new show create]
    resource :full_medical_checkups, only: %i[new show create]
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }
  has_one :easy_medical_checkup, dependent: :destroy
  has_one :full_medical_checkup, dependent: :destroy
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :redirect_unless_name, only: :index
  before_action :blocking_access_before_use, only: :before_use
  before_action :check_agreement, only: :before_use

  def index
    @user = User.find_by(name: session[:name])
  end

  def about; end

  def contact; end

  def before_use
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:name] = @user.name
      redirect_to root_path
    else
      cookies[:agree] = 'true'
      @agree = 'true'
      render :before_use
    end
  end

  def terms_of_use; end

  def privacy_policy; end

  def set_agreement
    cookies[:agree] = 'true'
    head :ok
  end

  private

  def check_agreement
    @agree = cookies[:agree] == 'true'
  end

  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/about.html.erb
<div class="row">
  <div class="col-lg-9 col-12">
    <h3><i class="bi bi-capsule"></i>さぷリカバーとは？</h3>
    <div class="mt-2 col-md-12">
      <p>さぷリカバーは健康診断の記録を入れることで、<br class="d-md-none">おすすめのサプリを提示してくれます。</p>
      <p>ただし、サプリメントは健康補助食品です。</p>
      <p>用法用量を守って正しい服用の上、<br class="d-md-none">運動や食生活など総合的な生活の見直しも行いましょう。</p>
    </div>
  </div>
</div>

app/views/users/before_use.html.erb
<% unless @agree %>
  <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="staticBackdropLabel">利用開始前に</h5>
        </div>
        <div class="modal-body">
          <%= render 'shared/terms_of_use' %>
        </div>
        <div class="form-check m-3">
          <input class="form-check-input" type="checkbox" value="" id="beforeUseCheckBox">
            <label class="form-check-label " for="beforeUseCheckBox">
              注意事項、利用規約に了承の上で利用を始める
            </label>
        </div>
        <div class="modal-footer">
          <%= link_to '利用をやめる', 'https://www.yahoo.co.jp/',class: "btn btn-quit", target: "_self" %>
          <div class="cursor-not-allowed">
            <button type="button" class="btn btn-agree" data-bs-dismiss="modal" id="modalButton" disabled>利用を始める</button>
          </div>
          </div>
      </div>
    </div>
  </div>
  <div class="row">
    <p>さぷリカバーは健康診断の記録を入れることで、<br class="d-lg-none">あなたにあったサプリをおすすめしてくれます。</p>
    <div class="col-sm-10 offset-sm-1 col-md-8 offset-md-2 mt-3">
      <%= form_with model:@user, local: true do |f| %>
        <div class="row">
          <div class="col-sm-9 mb-3">
            <div class="row align-items-center">
              <div class="col-sm-2">
                <%= f.label :name, class: "form-label" %>
              </div>
              <div class="col-sm-10">
                <%= f.text_field :name, class: "form-control" %>
              </div>
            </div>
          </div>
          <div class="col-sm-3 mb-3">
            <div class="d-grid gap-2 d-sm-block">
              <%= f.submit '先へすすむ',class: 'btn btn-signup' %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <%= javascript_pack_tag 'custom_modal' %>

<% else %>
  <div class="row">
    <p>さぷリカバーは健康診断の記録を入れることで、<br class="d-lg-none">あなたにあったサプリをおすすめしてくれます。</p>
    <div class="col-sm-10 offset-sm-1 col-md-8 offset-md-2 mt-3">
      <%= form_with model:@user, local: true do |f| %>
        <div class="row">
          <div class="col-sm-9 mb-3">
            <div class="row align-items-center">
              <div class="col-sm-2">
                <%= f.label :name, class: "form-label" %>
              </div>
              <div class="col-sm-10">
                <%= f.text_field :name, class: "form-control" %>
              </div>
            </div>
          </div>
          <div class="col-sm-3 mb-3">
            <div class="d-grid gap-2 d-sm-block">
              <%= f.submit '先へすすむ',class: 'btn btn-signup' %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/users/index.html.erb
<div class="row d-flex flex-column">
    <p>さぷリカバーは健康診断の記録を入れることで、</p>
    <p>あなたにあったサプリをおすすめしてくれます。</p>
  <div class="row checkup-area mt-5">
      <div class="d-grid gap-2 col-sm-5 mx-auto">
        <div class="checkup-btn">
          <%= link_to '簡易版', new_user_easy_medical_checkups_path(@user), class:'btn btn-easy-checkup text-nowrap d-grid gap-2', id:'easy_checkup' %>
        </div>
        <p class="text-center">検診結果を一部いれる</p>
      </div>
      <% if @user.easy_medical_checkup.present? %>
        <div class="checkup-btn col-sm-5 mx-auto mt-4 mt-sm-0">
          <%= link_to '完全版', new_user_full_medical_checkups_path(@user), class:'btn btn-full-checkup text-nowrap d-grid gap-2', id:'after_full_checkup' %>
          <p class="text-center">検診結果を全部いれる</p>
        </div>
      <% else %>
      <div class="cursor-not-allowed col-sm-5 mx-auto mt-4 mt-sm-0">
        <div class="checkup-btn">
          <%= link_to '完全版', new_user_full_medical_checkups_path(@user), class:'btn btn-full-checkup disabled text-nowrap d-grid gap-2', id:'before_full_checkup' %>
        </div>
          <p class="text-center"><s>検診結果を全部いれる</s></p>
          <p class="text-center"> 簡易版入力後に使えるよ！</p>
      </div>
    <% end %>
  </div>
</div>

app/views/users/privacy_policy.html.erb
<div class="row">
  <div class="col-lg-9 col-12">
    <h3>プライバシーポリシー</h3>
      <p>本サービス管理者（以下、「管理者」といいます。）は、本ウェブサイト上で提供するサービス（以下,「本サービス」といいます。）における、
      ユーザーの個人情報の取扱いについて、以下のとおりプライバシーポリシー（以下、「本ポリシー」といいます。）を定めます。</p>

    <h4>第1条（個人情報）</h4>
      <p>「個人情報」とは、個人情報保護法にいう「個人情報」を指すものとし、生存する個人に関する情報であって、
      当該情報に含まれる氏名、生年月日、住所、電話番号、連絡先その他の記述等により特定の個人を識別できる情報及び容貌、指紋、
      声紋にかかるデータ、及び健康保険証の保険者番号などの当該情報単体から特定の個人を識別できる情報（個人識別情報）を指します。</p>

    <h4>第2条（個人情報の収集方法）</h4>
      <p>当社は、ユーザーが利用登録をする際に氏名、生年月日、住所、電話番号、メールアドレス、
      銀行口座番号、クレジットカード番号、運転免許証番号などの個人情報をお尋ねすることがあります。
      また、ユーザーと提携先などとの間でなされたユーザーの個人情報を含む取引記録や決済に関する情報を、
      当社の提携先（情報提供元、広告主、広告配信先などを含みます。以下、｢提携先｣といいます。）などから収集することがあります。</p>

    <h4> 第3条（個人情報を収集・利用する目的）</h4>
      <p>当社が個人情報を収集・利用する目的は、以下のとおりです。</p>
      <ul class="list-wrap">
        <li>当社サービスの提供・運営のため</li>
        <li>ユーザーからのお問い合わせに回答するため（本人確認を行うことを含む）</li>
        <li>ユーザーが利用中のサービスの新機能、更新情報、キャンペーン等及び当社が提供する他のサービスの案内のメールを送付するため</li>
        <li>メンテナンス、重要なお知らせなど必要に応じたご連絡のため</li>
        <li>利用規約に違反したユーザーや、不正・不当な目的でサービスを利用しようとするユーザーの特定をし、ご利用をお断りするため</li>
        <li>ユーザーにご自身の登録情報の閲覧や変更、削除、ご利用状況の閲覧を行っていただくため</li>
        <li>有料サービスにおいて、ユーザーに利用料金を請求するため</li>
        <li>上記の利用目的に付随する目的</li>
      </ul>

    <h4>第4条（利用目的の変更）</h4>
      <p>当社は、利用目的が変更前と関連性を有すると合理的に認められる場合に限り、個人情報の利用目的を変更するものとします。</p>
      <p>利用目的の変更を行った場合には、変更後の目的について、当社所定の方法により、ユーザーに通知し、または本ウェブサイト上に公表するものとします。</p>

    <h4>第5条（個人情報の第三者提供）</h4>
      <p>当社は、次に掲げる場合を除いて、あらかじめユーザーの同意を得ることなく、第三者に個人情報を提供することはありません。</p>
      <p>ただし、個人情報保護法その他の法令で認められる場合を除きます。</p>
      <ul class="list-wrap">
        <li>人の生命、身体または財産の保護のために必要がある場合であって、本人の同意を得ることが困難であるとき</li>
        <li>公衆衛生の向上または児童の健全な育成の推進のために特に必要がある場合であって、本人の同意を得ることが困難であるとき</li>
        <li>国の機関もしくは地方公共団体またはその委託を受けた者が法令の定める事務を遂行することに対して協力する必要がある場合であって、本人の同意を得ることにより当該事務の遂行に支障を及ぼすおそれがあるとき </li>
        <li>予め次の事項を告知あるいは公表し、かつ当社が個人情報保護委員会に届出をしたとき</li>
        <ul class="list-wrap except">
          <li>利用目的に第三者への提供を含むこと</li>
          <li>第三者に提供されるデータの項目</li>
          <li>第三者への提供の手段または方法</li>
          <li>本人の求めに応じて個人情報の第三者への提供を停止すること</li>
          <li>本人の求めを受け付ける方法</li>
        </ul>
        <li>前項の定めにかかわらず、次に掲げる場合には、当該情報の提供先は第三者に該当しないものとします。</li>
        <ul class="list-wrap except">
          <li>当社が利用目的の達成に必要な範囲内において個人情報の取扱いの全部または一部を委託する場合</li>
          <li>合併その他の事由による事業の承継に伴って個人情報が提供される場合</li>
          <li>個人情報を特定の者との間で共同して利用する場合であって、その旨並びに共同して利用される個人情報の項目、
          共同して利用する者の範囲、利用する者の利用目的および当該個人情報の管理について責任を有する者の氏名または名称について、
          あらかじめ本人に通知し、または本人が容易に知り得る状態に置いた場合</li>
        </ul>
      </ul>

    <h4>第6条（個人情報の開示）</h4>
      <p>当社は、本人から個人情報の開示を求められたときは、本人に対し、遅滞なくこれを開示します。</p>
      <p>ただし、開示することにより次のいずれかに該当する場合は、
      その全部または一部を開示しないこともあり、開示しない決定をした場合には、その旨を遅滞なく通知します。</p>
      <p>なお、個人情報の開示に際しては、1件あたり1、000円の手数料を申し受けます。</p>
      <ul class="list-wrap">
        <li>本人または第三者の生命、身体、財産その他の権利利益を害するおそれがある場合</li>
        <li>当社の業務の適正な実施に著しい支障を及ぼすおそれがある場合</li>
        <li>その他法令に違反することとなる場合</li>
      </ul>
      <p>前項の定めにかかわらず、履歴情報および特性情報などの個人情報以外の情報については、原則として開示いたしません。</p>

    <h4>第7条（個人情報の訂正および削除）</h4>
      <p>ユーザーは、当社の保有する自己の個人情報が誤った情報である場合には、当社が定める手続きにより、当社に対して個人情報の訂正、追加または削除（以下、「訂正等」といいます。）を請求することができます。</p>
      <p>当社は、ユーザーから前項の請求を受けてその請求に応じる必要があると判断した場合には、遅滞なく、当該個人情報の訂正等を行うものとします。</p>
      <p>当社は、前項の規定に基づき訂正等を行った場合、または訂正等を行わない旨の決定をしたときは遅滞なく、これをユーザーに通知します。</p>

    <h4>第8条（個人情報の利用停止等）</h4>
      <p>当社は、本人から、個人情報が、利用目的の範囲を超えて取り扱われているという理由、または不正の手段により取得されたものであるという理由により、
      その利用の停止または消去（以下、「利用停止等」といいます。）を求められた場合には、遅滞なく必要な調査を行います。</p>
      <p>前項の調査結果に基づき、その請求に応じる必要があると判断した場合には、遅滞なく、当該個人情報の利用停止等を行います。</p>
      <p>当社は、前項の規定に基づき利用停止等を行った場合、または利用停止等を行わない旨の決定をしたときは、遅滞なく、これをユーザーに通知します。</p>
      <p>前2項にかかわらず、利用停止等に多額の費用を有する場合その他利用停止等を行うことが困難な場合であって、
      ユーザーの権利利益を保護するために必要なこれに代わるべき措置をとれる場合は、この代替策を講じるものとします。</p>

    <h4>第9条（プライバシーポリシーの変更）</h4>
      <p>本ポリシーの内容は、法令その他本ポリシーに別段の定めのある事項を除いて、ユーザーに通知することなく、変更することができるものとします。</p>
      <p>当社が別途定める場合を除いて、変更後のプライバシーポリシーは、本ウェブサイトに掲載したときから効力を生じるものとします。</p>

    <h4>第10条（お問い合わせ窓口）</h4>
      <p>本ポリシーに関するお問い合わせは、下記の窓口までお願いいたします。</p>

    <div class="contact">
      <%= link_to 'https://twitter.com/841wtb' do %>
        <%= image_tag('xlogo.png', alt: 'X(Twitter)', size: '35x35') %>
        アプリ制作者X(twitter)
      <% end %>
    </div>
  </div>
</div>

app/views/users/terms_of_use.html.erb
<div class="row">
  <div class="col-lg-9 col-12">
    <h2>アプリ利用時の注意事項</h2>
    <%= render 'shared/terms_of_use' %>
  </div>
</div>