config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  get 'about', to: 'users#about'
  get 'before_use', to: 'users#before_use'
  get 'terms_of_use', to: 'users#terms_of_use'
  get 'privacy_policy', to: 'users#privacy_policy'
  post 'set_agree_cookie', to: 'users#set_agreement'
  resources :users, only: %i[index create] do
    resource :easy_medical_checkups, only: %i[new show create]
    resource :full_medical_checkups, only: %i[new show create]
  end
end

app/views/shared/_error_message.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger">
    <ul class="list-unstyled mb-0">
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <%= message %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="container footer">
  <ul class="footer-list">
    <li><%= link_to '利用規約', terms_of_use_path %></li>
    <li><%= link_to 'プライバシーポリシー',privacy_policy_path  %></li>
  </ul>
  <p><small>© 2023-2024 - supprecover. All rights reserved.</small></p>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-light">
  <div class="container">
      <%= link_to root_path, class: "navbar-brand p-3" do %>
        <i class="bi bi-capsule"></i> <span class="navbar-brand h1">さぷリカバー</span>
      <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <li class="nav-item">
          <% if current_page?(root_path) %>
            <%= link_to 'Home', root_path, class: "nav-link active", aria: { current: 'page' } %>
          <% else %>
            <%= link_to 'Home', root_path, class: "nav-link" %>
          <% end %>
        </li>
        <li class="nav-item">
          <% if current_page?(about_path) %>
            <%= link_to 'About', about_path, class:"nav-link active", aria: { current: 'page' } %>
          <% else %>
          <%= link_to 'About', about_path, class:"nav-link" %>
          <% end %>
        </li>
        <li class="nav-item">
        <%= link_to 'Contact', 'https://twitter.com/841wtb', class:"nav-link",target: :_blank %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_progress_bar.html.erb
<div class="progress-container" id="progressContainer">
  <div class="progress-bar" id="loadingBar"></div>
</div>

app/views/shared/_terms_of_use.html.erb
<div class="row">
  <div class="col-lg-9 col-12">
    <h3>利用規約</h3>
      <p>この利用規約(以下、「本規約」といいます。)は、本サービス(本サイトを含むものとし、以下、特に両者を区別しません。)の利用条件を定めるものです。</p>
      <p>本規約は、本サービスを利用するすべてのユーザーに適用されます。</p>

    <h4>本規約への同意</h4>
      <p>ユーザーは、本サービスを利用することによって、本規約に有効かつ取り消し不能な同意をしたものとみなされます。</p>
      <p>本規約に同意しないユーザーは、本サービスをご利用いただけません。</p>

    <h4>利用登録</h4>
      <p>本サービスの利用を希望する方は、本規約に同意の上、本サービス管理者の定める方法によって利用登録を申請し、
      本サービス管理者がこれを承認することによって、本サービスの利用登録をすることができます。</p>

    <h4>登録拒否</h4>
      <p>本サービス管理者は、以下のいずれかの事由があると判断した場合、利用登録の申請を承認しないことがあります。</p>
      <p>本サービス管理者は登録拒否の理由について一切の開示義務を負いません。</p>
      <ul class="list-wrap">
        <li>利用者が未成年である場合</li>
        <li>虚偽の事項を届け出た場合</li>
        <li>本規約に違反したことがある者からの申請である場合</li>
        <li>その他、本サービス管理者が利用登録を相当でないと判断した場合</li>
        <li>ユーザーが本規約に違反した場合</li>
        <li>その他本サービス管理者とユーザーの信頼関係が損なわれたと本サービス管理者が判断する場合</li>
      </ul>

    <h4>コンテンツのご利用</h4>
      <p>本サービス管理者はユーザーに対し、本サービスが提供する文章、画像、動画、音声、音楽、ソフトウェア、プログラム、コードその他のコンテンツについて、
      本サービスの利用範囲内における私的な利用を許諾します。</p>
      <p>有償コンテンツについては、本サービス管理者が定める利用料金の支払が完了した場合に、
      本サービスの利用範囲内における私的な利用を許諾します。</p>
      <p>これは、譲渡及び再許諾できない非独占的な利用権です。</p>
      <p>この範囲を超えて本サービスが提供するコンテンツを利用することは一切禁止します。</p>
      理由の如何を問わず、ユーザーが本サービスを利用する権利を失った場合、
      <p>本サービスの一切のコンテンツの利用ができなくなることをユーザーは予め承諾するものとします。</p>

    <h4>広告の表示</h4>
      <p>本サービス管理者は、本サービスに本サービス管理者または第三者の広告を掲載することができるものとします。</p>

      <h4>禁止事項</h4>
      <p>ユーザーは、本サービスの利用にあたり、以下の行為をしてはなりません。</p>
      <ul>
        <li>法令、裁判所の判決、決定若しくは命令、又は法令上拘束力のある行政措置に違反する行為又はこれらを助長する行為</li>
      </ul>

    <h4>犯罪行為に関連する行為</h4>
      <ul class="list-wrap">
        <li>本サービス管理者や第三者の知的財産権を侵害する行為</li>
        <li> 本サービス管理者や第三者の肖像権、プライバシー、名誉、その他の権利又は利益を侵害する行為</li>
        <li>本サービス管理者や第三者のサーバーまたはネットワークに過度の負担をかけたり、その正常な作動を妨害する行為</li>
        <li>本サービス管理者のサービスの運営を妨害するおそれのある行為</li>
        <li>不正アクセスをし、またはこれを試みる行為</li>
        <li>逆アセンブル、逆コンパイル、リバースエンジニアリング等によって本サービスのソースコードを解析する行為</li>
        <li>本サービスに接続しているシステムに権限なく不正にアクセスし又は本サービス管理者設備に蓄積された情報を不正に書き換え若しくは消去する行為</li>
        <li>本サービスのウェブサイトやソフトウェアを複製、送信、譲渡、貸与又は改変する行為</li>
        <li>本サービス上のアカウント又はコンテンツを第三者に有償で貸与、譲渡、売買等をする行為</li>
        <li>本サービスによって得られた情報を商業的に利用する行為</li>
        <li>本サービス管理者が意図しない方法によって本サービスに関連して利益を得ることを目的とする行為</li>
        <li>本サービス管理者が許諾しない本サービス上での宣伝、広告、勧誘、または営業行為</li>
        <li>他のユーザーに関する個人情報等を収集または蓄積する行為</li>
        <li>違法、不正又は不当な目的を持って本サービスを利用する行為</li>
        <li>本サービスの他のユーザーまたはその他の第三者に不利益、損害、不快感を与える行為</li>
        <li>他のユーザーに成りすます行為</li>
        <li>他のユーザーのアカウントを利用する行為</li>
        <li>面識のない異性との出会いを目的とした行為</li>
        <li>反社会的勢力に対して直接または間接に利益を供与する行為</li>
        <li>公序良俗に違反する行為</li>
        <li>歩行中、車両運転中、その他本サービスの利用が不適切な状況又は態様において本サービスを利用する行為</li>
        <li>その他、本サービス管理者が不適切と判断する行為</li>
      </ul>

    <h4>反社会的勢力の排除</h4>
      <p>ユーザーは、次の各号のいずれにも該当しないことを表明し、かつ将来にわたっても該当しないことを表明し、保証するものとします。</p>
      <ul class="list-wrap">
        <li>自ら（法人その他の団体にあっては、自らの役員を含みます。）が、暴力団、暴力団員、暴力団員でなくなった時から5年を経過しない者</li>
        <li>暴力団準構成員、暴力団関係企業、総会屋、社会運動等標ぼうゴロまたは特殊知能暴力集団等その他これらに準じる者（以下総称して「暴力団員等」といいます。）であること</li>
        <li>ユーザーが法人その他の団体の場合にあっては、暴力団員等が経営を支配していると認められる関係を有すること</li>
        <li>ユーザーが法人その他の団体の場合にあっては、暴力団員等が経営に実質的に関与していると認められる関係を有すること</li>
        <li>自らもしくは第三者の不正の利益を図る目的または第三者に損害を加える目的をもって取引を行うなど、暴力団員等を利用していると認められる関係を有すること</li>
        <li>暴力団員等に対して資金等を提供し、または便宜を供与するなどの関与をしていると認められる関係を有すること</li>
        <li>ユーザーが法人その他の団体の場合にあっては、自らの役員または自らの経営に実質的に関与している者が暴力団員等と社会的に非難されるべき関係を有すること</li>
      </ul>
      <p>ユーザーは、自らまたは第三者を利用して次の各号のいずれか一にでも該当する行為を行わないことを保証するものとします。</p>

    <h4>暴力的な要求行為</h4>
      <ul class="list-wrap">
        <li>法的な責任を超えた不当な要求行為</li>
        <li>取引に関して、脅迫的な言動をし、または暴力を用いる行為</li>
        <li>風説を流布し、偽計を用い、または威力を用いて、本サービス管理者の信用を毀損し、または本サービス管理者の業務を妨害する行為</li>
        <li>その他前各号に準ずる行為</li>
      </ul>

    <h4>利用制限</h4>
      <p>本サービス管理者は、ユーザーが以下のいずれかに該当する場合には、事前の通知なく、ユーザーに対して本サービスの全部もしくは一部の利用を制限し、
      またはユーザーとしての登録を抹消することができるものとします。</p>
      <p>本サービス管理者は、本条に基づき本サービス管理者が行った行為によりユーザーに生じた損害について、一切の責任を負いません。</p>
      <ul class="list-wrap">
        <li>本規約のいずれかの条項に違反した場合</li>
        <li>登録事項に虚偽の事実があることが判明した場合</li>
        <li>本サービス管理者からの連絡に対し、相当の期間が経過しても返答がない場合</li>
        <li>最終のご利用日から相当期間、本サービスのご利用がない場合</li>
        <li>反社会的勢力等であるか、反社会的勢力等との何らかの交流若しくは関与を行っていると本サービス管理者が判断した場合</li>
        <li>その他、本サービス管理者が本サービスの利用を適当でないと判断した場合</li>
      </ul>

    <h4>本サービスの提供の停止</h4>
      <p>本サービス管理者は、以下のいずれかの事由があると判断した場合、ユーザーに事前に通知することなく本サービスの全部または一部の提供を停止または中断することができるものとします。</p>
      <p>本サービス管理者は、この場合にユーザーまたは第三者が被ったいかなる不利益または損害についても、一切の責任を負わないものとします。</p>
      <ul class="list-wrap">
        <li>本サービスにかかるコンピュータシステムの保守点検または更新を行う場合</li>
        <li>地震、落雷、火災、停電、天災またはウィルスの蔓延などの不可抗力により、本サービスの提供が困難となった場合</li>
        <li>コンピュータまたは通信回線等が事故により停止した場合</li>
        <li>その他、本サービス管理者が本サービスの提供が困難と判断した場合</li>
      </ul>

    <h4>保証の否認</h4>
      <p>本サービス管理者は、本サービスや本サービスが提供するコンテンツに、システムバグや第三者の権利侵害が含まれないことを保証するものではありません。</p>
      <p>また、安全性、信頼性、正確性、完全性、有効性、特定の目的への適合性を保証するものでもありません。</p>

    <h4>免責</h4>
      <p>本サービス管理者は、本サービスに関してユーザーに生じたあらゆる損害について一切の責任を負いません。</p>
      <p>ただし、本サービスに関する本サービス管理者とユーザーとの間の契約（本規約を含みます。）が消費者契約法に定める消費者契約となる場合、この免責規定は適用されません。</p>
      <p>消費者契約に該当する場合であっても、本サービス管理者は、本サービス管理者の過失（重過失を除きます。）によって
      ユーザーに生じた損害のうち特別の事情から生じた損害（本サービス管理者またはユーザーが損害発生につき予見し、または予見し得た場合を含みます。）について、
      一切の責任を負いません。ユーザーと他のユーザーまたは第三者との間において生じたトラブルについても一切責任を負いません。</p>
      <p>本サービス管理者は、本サービスに関してユーザーが被った損害につき、賠償する責任を負わないものとします。</p>

    <h4>サービス内容の変更</h4>
      <p>本サービス管理者は、ユーザーに通知することなく、本サービスの内容を変更したり、本サービスの提供を中止、終了することができるものとします。</p>
      <p>本サービス管理者は、これによってユーザーに生じた損害について一切の責任を負いません。</p>

    <h4>利用規約の変更</h4>
      <p>本サービス管理者は、ユーザーに通知することなく、いつでも本規約を変更することができるものとします。</p>
      <p>変更後の本規約は、本サービス管理者ウェブサイトに掲示された時点から効力を生じるものとします。</p>
      <p>本規約の変更後、本サービスの利用を継続したユーザーは、変更後の本規約に同意したものとみなします。</p>

    <h4>個人情報の取扱い</h4>
      <p>本サービスの利用によって取得するユーザーの個人情報については、本サービス管理者のプライバシーポリシーに従い適切に取り扱うものとします。</p>

    <h4>通知または連絡</h4>
      <p>ユーザーと本サービス管理者との間の通知または連絡は、本サービス管理者の定める方法によって行うものとします。</p>
      <p>本サービス管理者は、ユーザーから、本サービス管理者が別途定める方式に従った変更届け出がない限り、
      現在登録されている連絡先が有効なものとみなして当該連絡先へ通知または連絡を行い、これらは、発信時にユーザーへ到達したものとみなします。</p>

    <h4>権利義務の譲渡</h4>
      <p>ユーザーは、本サービス管理者の書面による事前の承諾なく、利用契約上の地位または本規約に基づく権利もしくは義務を第三者に譲渡し、または担保に供することはできません。</p>

    <h4>事業譲渡</h4>
      <p>本サービス管理者は本サービスにかかる事業を他社に事業譲渡（事業譲渡、会社分割その他事業が移転するあらゆる場合を含みます。）した場合には、
      当該事業譲渡に伴い利用契約上の地位、本規約に基づく権利及び義務並びにユーザーの情報を当該事業譲渡の譲受人に譲渡することができるものとします。</p>
      <p>ユーザーは、かかる譲渡につき予め同意したものとみなします。</p>

    <h4>適用関係</h4>
      <p>本規約は、ユーザーと本サービス管理者との間の本サービスの利用に関わる一切の関係に適用されるものとします。</p>
      <p>本サービス管理者は本サービスに関し、本規約のほか、ご利用にあたってのルールを定めることがあります。</p>
      <p>これらのルールは、その名称のいかんに関わらず、本規約の一部を構成するものとします。</p>
      <p>本規約がこれらのルールと矛盾する場合には、これらのルールが優先して適用されるものとします。</p>

    <h4>分離可能性</h4>
      <p>本規約のいずれかの条項又はその一部が無効又は執行不能と判断された場合であっても、
      当該判断は他の部分に影響を及ぼさず、本規約の残りの部分は、引き続き有効かつ執行力を有するものとします。</p>

    <h4>準拠法・裁判管轄</h4>
      <p>本規約の解釈にあたっては、日本法を準拠法とします。</p>
      <p>本サービスに関して紛争が生じた場合には、本サービス管理者の本店所在地を管轄する地方裁判所を専属的合意管轄とします。</p>
      <p>以上</p>
      <p>以上の注意事項にすべて同意の上で利用します。</p>
  </div>
</div>