config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  get 'about', to: 'users#about'
  get 'before_use', to: 'users#before_use'
  get 'terms_of_use', to: 'users#terms_of_use'
  get 'privacy_policy', to: 'users#privacy_policy'
  post 'set_agree_cookie', to: 'users#set_agreement'
  resources :users, only: %i[index create] do
    resource :easy_medical_checkups, only: %i[new show create]
    resource :full_medical_checkups, only: %i[new show create]
  end
end

app/models/easy_medical_checkup.rb
class EasyMedicalCheckup < ApplicationRecord
  validates :height, numericality: { greater_than_or_equal_to: 140, less_than_or_equal_to: 200, allow_blank: true },
                     presence: true
  validates :weight, numericality: { greater_than_or_equal_to: 40, less_than_or_equal_to: 150, allow_blank: true },
                     presence: true
  validates :blood_pressure_up, numericality: { only_integer: true, allow_blank: true }, presence: true
  validates :blood_pressure_down, numericality: { only_integer: true, allow_blank: true }, presence: true
  validates :total_cholesterol, numericality: { only_integer: true, allow_blank: true }, presence: true
  validates :hdl_cholesterol, numericality: { only_integer: true, allow_blank: true }, presence: true
  validates :ldl_cholesterol, numericality: { only_integer: true, allow_blank: true }, presence: true
  validates :neutral_fat, numericality: { only_integer: true, allow_blank: true }, presence: true
  validates :ast, numericality: { only_integer: true, allow_blank: true }, presence: true
  validates :alt, numericality: { only_integer: true, allow_blank: true }, presence: true
  validates :gamma_gtp, numericality: { only_integer: true, allow_blank: true }, presence: true
  belongs_to :user
  has_many :taggings
  has_many :tags, through: :taggings

  def bmi
    (weight / ((height / 100.0)**2)).round(1) # BMI ＝ 体重kg ÷ (身長m)2
  end

  def body_type
    case bmi
    when 0...18.5
      'やせ型'
    when 18.5...25
      '標準'
    when 25...30
      '肥満(軽)'
    else
      '肥満(重)'
    end
  end

  def recommended_supplements
    bad_ranking = {}

    if self.blood_pressure_up > Rails.configuration.x.reference_values[:blood_pressure_up][:max]
      bad_ranking[:blood_pressure_up] = (self.blood_pressure_up.to_f / Rails.configuration.x.reference_values[:blood_pressure_up][:max]) * 100
    elsif self.blood_pressure_up < Rails.configuration.x.reference_values[:blood_pressure_up][:min]
      bad_ranking[:blood_pressure_up] = (self.blood_pressure_up.to_f / Rails.configuration.x.reference_values[:blood_pressure_up][:min]) * 100
    end

    if self.blood_pressure_down > Rails.configuration.x.reference_values[:blood_pressure_down][:max]
      bad_ranking[:blood_pressure_down] = (self.blood_pressure_down.to_f/ Rails.configuration.x.reference_values[:blood_pressure_down][:max]) * 100
    elsif self.blood_pressure_down < Rails.configuration.x.reference_values[:blood_pressure_down][:min]
      bad_ranking[:blood_pressure_down] = (self.blood_pressure_down.to_f / Rails.configuration.x.reference_values[:blood_pressure_down][:min]) * 100
    end

    if self.total_cholesterol > Rails.configuration.x.reference_values[:total_cholesterol][:max]
      bad_ranking[:total_cholesterol] = (self.total_cholesterol.to_f / Rails.configuration.x.reference_values[:total_cholesterol][:max]) * 100
    elsif self.total_cholesterol < Rails.configuration.x.reference_values[:total_cholesterol][:min]
      bad_ranking[:total_cholesterol] = (self.total_cholesterol.to_f / Rails.configuration.x.reference_values[:total_cholesterol][:min]) * 100
    end

    if self.hdl_cholesterol > Rails.configuration.x.reference_values[:hdl_cholesterol][:max]
      bad_ranking[:hdl_cholesterol] = (self.hdl_cholesterol.to_f / Rails.configuration.x.reference_values[:hdl_cholesterol][:max]) * 100
    elsif self.hdl_cholesterol < Rails.configuration.x.reference_values[:hdl_cholesterol][:min]
      bad_ranking[:hdl_cholesterol] = (self.hdl_cholesterol.to_f / Rails.configuration.x.reference_values[:hdl_cholesterol][:min]) * 100
    end

    if self.ldl_cholesterol > Rails.configuration.x.reference_values[:ldl_cholesterol][:max]
      bad_ranking[:ldl_cholesterol] = (self.ldl_cholesterol.to_f / Rails.configuration.x.reference_values[:ldl_cholesterol][:max]) * 100
    elsif self.ldl_cholesterol < Rails.configuration.x.reference_values[:ldl_cholesterol][:min]
      bad_ranking[:ldl_cholesterol] = (self.ldl_cholesterol.to_f / Rails.configuration.x.reference_values[:ldl_cholesterol][:min]) * 100
    end

    if self.neutral_fat > Rails.configuration.x.reference_values[:neutral_fat][:max]
      bad_ranking[:neutral_fat] = (self.neutral_fat.to_f / Rails.configuration.x.reference_values[:neutral_fat][:max]) * 100
    elsif self.neutral_fat < Rails.configuration.x.reference_values[:neutral_fat][:min]
      bad_ranking[:neutral_fat] = (self.neutral_fat.to_f / Rails.configuration.x.reference_values[:neutral_fat][:min]) * 100
    end

    if self.ast > Rails.configuration.x.reference_values[:ast][:max]
      bad_ranking[:ast] = (self.ast.to_f / Rails.configuration.x.reference_values[:ast][:max]) * 100
    elsif self.ast < Rails.configuration.x.reference_values[:ast][:min]
      bad_ranking[:ast] = (self.ast.to_f / Rails.configuration.x.reference_values[:ast][:min]) * 100
    end

    if self.alt > Rails.configuration.x.reference_values[:alt][:max]
      bad_ranking[:alt] = (self.alt.to_f / Rails.configuration.x.reference_values[:alt][:max]) * 100
    elsif self.alt < Rails.configuration.x.reference_values[:alt][:min]
      bad_ranking[:alt] = (self.alt.to_f / Rails.configuration.x.reference_values[:alt][:min]) * 100
    end

    if self.gamma_gtp > Rails.configuration.x.reference_values[:gamma_gtp][:max]
      bad_ranking[:gamma_gtp] = (self.gamma_gtp.to_f / Rails.configuration.x.reference_values[:gamma_gtp][:max]) * 100
    elsif self.gamma_gtp < Rails.configuration.x.reference_values[:gamma_gtp][:min]
      bad_ranking[:gamma_gtp] = (self.gamma_gtp.to_f / Rails.configuration.x.reference_values[:gamma_gtp][:min]) * 100
    end

    sorted_bad_rankings = bad_ranking.sort_by { |_key, value| -(value - 100).abs }.to_h

    recommendations = []

    sorted_bad_rankings.each do |key, value|
      up_or_down = value > 100 ? 'uptodown' : 'downtoup'
      recommendations += Tag.where(name: key, up_or_down: up_or_down).map(&:supplements)
    end

    if body_type == 'やせ型'
      weight_tag = Tag.find_by(name: 'weight', up_or_down: 1)
    elsif body_type == '肥満(軽)' || body_type == '肥満(重)'
      weight_tag = Tag.find_by(name: 'weight', up_or_down: 0)
    end

    recommendations += weight_tag.supplements if weight_tag

    recommendations.flatten!
    recommendations.uniq!
    Supplement.where(id: recommendations.map(&:id))
  end
end

app/controllers/easy_medical_checkup_controller.rb
class EasyMedicalCheckupController < ApplicationController

  def index
    @user = User.find_by(name: session[:name])
    @easy_medical_checkup = EasyMedicalCheckup.new
    @easy_medical_checkup.user_id = @user.id
  end

  def create
    @user = User.find_by(name: session[:name])
    @easy_medical_checkup = EasyMedicalCheckup.new(easy_medical_checkup_params)
    @easy_medical_checkup.user_id = @user.id
    if @easy_medical_checkup.save
      redirect_to easy_medical_checkup_path(@easy_medical_checkup.id)
    else
      render :index
    end
  end

  def show
    @user = User.find_by(name: session[:name])
    @easy_medical_checkup = EasyMedicalCheckup.find_by(user_id: @user.id)
    @recommended_supplements = @easy_medical_checkup.recommended_supplements
    supplement_names = @recommended_supplements.map(&:name).join('、')
    @tweet_template = "#{@easy_medical_checkup.user.name}さんへのおすすめサプリは、#{supplement_names}です！診断結果をチェックしてみてね！"
    if @tweet_template.length > 280
      truncated_text = tweet_template[0..276] + "..."
      @result_for_tweet = truncated_text
    else
      @result_for_tweet = @tweet_template
    end
  end

  private

  def easy_medical_checkup_params
    params.require(:easy_medical_checkup).permit(:height, :weight, :blood_pressure_up, :blood_pressure_down,
                                                  :total_cholesterol, :hdl_cholesterol, :ldl_cholesterol, :neutral_fat,
                                                  :ast, :alt, :gamma_gtp)
  end
end

app/controllers/easy_medical_checkups_controller.rb
class EasyMedicalCheckupsController < ApplicationController
  before_action :redirect_unless_name
  before_action :set_user
  def new
    @easy_medical_checkup = EasyMedicalCheckup.new
    @easy_medical_checkup.user_id = @user.id
  end

  def create
    @easy_medical_checkup = @user.easy_medical_checkup || @user.build_easy_medical_checkup
    if @easy_medical_checkup.update(easy_medical_checkup_params)
      redirect_to user_easy_medical_checkups_path(@user)
    else
      render :new
    end
  end

  def show
    @easy_medical_checkup = EasyMedicalCheckup.find_by(user_id: @user.id)
    @recommended_supplements_easy = @easy_medical_checkup.recommended_supplements
    supplement_names = @recommended_supplements_easy.map(&:name).join('、')
    @tweet_template = "#{@easy_medical_checkup.user.name}さんへのおすすめサプリは、#{supplement_names}です！診断結果をチェックしてみてね！"
    view_context.tweet_truncate
  end

  private

  def easy_medical_checkup_params
    params.require(:easy_medical_checkup).permit(:height, :weight, :blood_pressure_up, :blood_pressure_down,
                                                 :total_cholesterol, :hdl_cholesterol, :ldl_cholesterol, :neutral_fat,
                                                 :ast, :alt, :gamma_gtp)
  end
end

app/helpers/easy_medical_checkups_helper.rb
module EasyMedicalCheckupsHelper
end

app/views/easy_medical_checkup/index.html.erb
<%= render 'shared/error_message', object: @easy_medical_checkup %>
  <%= form_with model:@easy_medical_checkup, url: easy_medical_checkup_index_path, local: true, class: "checkup_form" do |f| %>
    <div class="form-group mb-4">
    <%= f.label :height, EasyMedicalCheckup.human_attribute_name(:height) %>
    <%= f.select :height, 140..200,{ include_blank: '選択して下さい' }, {class: "form-control"}%>
    </div>

    <div class="form-group mb-4">
    <%= f.label :weight, EasyMedicalCheckup.human_attribute_name(:weight) %>
    <%= f.select :weight, 40..150,{ include_blank: '選択して下さい' }, {class: "form-control"}%>
    </div>

    <div class="form-group mb-4">
    <%= f.label :blood_pressure_up, EasyMedicalCheckup.human_attribute_name(:blood_pressure_up) %>
    <%= f.text_field :blood_pressure_up, class: "form-control" %>
    </div>

    <div class="form-group mb-4">
    <%= f.label :blood_pressure_down, EasyMedicalCheckup.human_attribute_name(:blood_pressure_down) %>
    <%= f.text_field :blood_pressure_down, class: "form-control" %>
    </div>

    <div class="form-group mb-4">
    <%= f.label :total_cholesterol, EasyMedicalCheckup.human_attribute_name(:total_cholesterol) %>
    <%= f.text_field :total_cholesterol, class: "form-control" %>
    </div>

    <div class="form-group mb-4">
    <%= f.label :hdl_cholesterol, EasyMedicalCheckup.human_attribute_name(:hdl_cholesterol) %>
    <%= f.text_field :hdl_cholesterol, class: "form-control" %>
    </div>

    <div class="form-group mb-4">
    <%= f.label :ldl_cholesterol, EasyMedicalCheckup.human_attribute_name(:ldl_cholesterol) %>
    <%= f.text_field :ldl_cholesterol,class: "form-control" %>
    </div>

    <div class="form-group mb-4">
    <%= f.label :neutral_fat, EasyMedicalCheckup.human_attribute_name(:neutral_fat) %>
    <%= f.text_field :neutral_fat, class: "form-control" %>
    </div>

    <div class="form-group mb-4">
    <%= f.label :ast, EasyMedicalCheckup.human_attribute_name(:ast) %>
    <%= f.text_field :ast, class: "form-control" %>
    </div>

    <div class="form-group mb-4">
    <%= f.label :alt, EasyMedicalCheckup.human_attribute_name(:alt) %>
    <%= f.text_field :alt, class: "form-control" %>
    </div>

    <div class="form-group mb-4">
    <%= f.label :gamma_gtp, EasyMedicalCheckup.human_attribute_name(:gamma_gtp) %>
    <%= f.text_field :gamma_gtp, class: "form-control" %>
    </div>

    <%= f.submit '送信', class: 'btn btn-primary' %>

  <% end %>